### ISSUE TITLE
setting Category separator is missing in the configuartion windows

### ISSUE THREAD

**Issue by 5axes** [ChristopherHoffman/3d-print-log-cura-plugin#10]
Cura 5.0
Plugin release : 2.0.2

The Settings separator is missing in the configuration Windows.

![image](https://user-images.githubusercontent.com/11015345/176873798-e542503c-5375-4aae-b880-e9eaa1008843.png)

Working code to solved the problem in the SettingsCategory.qml file (QT6)

`
import QtQuick 2.2
import QtQuick.Controls 2.1

import Cura 1.5 as Cura
import UM 1.5 as UM
import ".."

Cura.CategoryButton
{
    id: base;

    categoryIcon: definition ? UM.Theme.getIcon(definition.icon) : ""
    labelText: definition ? definition.label : ""
    expanded: definition ? definition.expanded : false

    signal showTooltip(string text)
    signal hideTooltip()
    signal contextMenuRequested()

    onClicked: expanded ? settingDefinitionsModel.collapseRecursive(definition.key) : settingDefinitionsModel.expandRecursive(definition.key)
}
`

![image](https://user-images.githubusercontent.com/11015345/176874659-1bb09b2c-f26d-4d63-ad15-b32457e9dfd9.png)
[SettingCategory.txt](https://github.com/ChristopherHoffman/3d-print-log-cura-plugin/files/9028054/SettingCategory.txt)

**Comment by ChristopherHoffman** [comment]
Ah, I appreciate the bug report and the suggested fix. I'll take a look at it and push out an update. Thank you!
