### ISSUE TITLE
Feature suggest: Image upload

### ISSUE THREAD

**Issue by cospav** [ChristopherHoffman/3d-print-log-cura-plugin#4]
Thanks for this interesting plugin, I didn't really used it yet - but it looks very promising.

I would like to see a preview pic inside the logged details, but I find it quite cumbersome if I need to save images on disk and upload them later.

So just a question:
Is there no direct way (imho from the Cura extension api) to grab a preview of the cure graphic?

(Another workaround would be, to allow screenshots from clipboard pasted into the html page....)

Thanks for reading in advance!
CosPav

**Comment by ChristopherHoffman** [comment]
Thank you for taking the time to send some feedback. I think those are both great ideas. I agree that its cumbersome to have to save a screenshot to disk and then upload. I'll add a copy/paste mechanic to make it easier to upload screenshots to 3D Print Log.

I also never thought about having Cura upload an initial image. I know Cura has the ability to take basic screenshots, they use it as a preview on their Ultimaker screens when selecting gcode files. I'll have to do some research to see if they expose that in a way that the plugin can utilize it.

I'll leave this issue open and use it for tracking the screenshot-from-cura-plugin.

**Comment by cospav** [comment]
Well Christopher, the new snapshot feature works like a charm. Very nice implemented without any hazzle for the user. A great enhancement for your plugin, Thank you for the effort!

**Comment by ChristopherHoffman** [comment]
Thank you for the great idea, I think many users will find it extremely useful! If you have any other suggestions, please let me know.
