### ISSUE TITLE
[Request] Add default behaviour option

### ISSUE THREAD

**Issue by m-roberts** [ChristopherHoffman/3d-print-log-cura-plugin#6]
Currently, the confirmation dialog is offered every time.

It would be great if it were possible to offer the ability to choose between the following behaviours:
* Always open
* Never open
* Always ask

This would allow for avoiding an unnecessary manual input step and easy disabling (without needing to uninstall).

**Comment by ChristopherHoffman** [comment]
This is a great idea. I originally implemented a checkbox for this behavior in version 2.0.1, but after thinking about it, this suggestion of a dropdown is far more useful. It'll be released in version 2.0.2 soon.

**Comment by m-roberts** [comment]
@ChristopherHoffman - great, thanks! Is it worth including something on this in the README?
